# Generated by Django 5.0.4 on 2024-05-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_topic_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
